### ISSUE TITLE
Correcting the generated tracks?

### ISSUE THREAD

**Issue by sgomezr** [motr/motr#6]
Hi :) Is there any way of modifying parts of the output tracks if we consider the generated tracks to be faulty?

**Comment by adamltaylor** [comment]
Yes, there's a program called Catalytic that can be used for this.  Simply type:

catalytic

at the Matlab prompt once Motr has been installed.  This will bring up a GUI that enables one to correct the tracks from Motr.  Documentation for Catalytic is pretty sparse, however.  But Catalytic was forked from Ctrax's FixErrors GUI, so the documentation for that may be of some help:

http://ctrax.sourceforge.net/fixerrors.html

If you have further questions, please e-mail them to motr@janelia.hhmi.org.

**Comment by sgomezr** [comment]
Thanks so much!
