### ISSUE TITLE
I couldn't run Motr

### ISSUE THREAD

**Issue by enverahmet** [motr/motr#7]
Firstly, I have to say that I'm just an end-user and know nothing more than clicking and typing on computers. I've installed Microsoft SDK 7.1 with MatLab R2014a on a Windows 10 x86 PC. When I tried to run Motr, the error message below appeared:
***
Error using mex
parsejpg8.c
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(61) : error C2065: 'off_t' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(61) : error C2146: syntax error : missing ';' before
identifier 'offset'
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(61) : error C2065: 'offset' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(62) : error C2143: syntax error : missing ';' before
'type'
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(85) : error C2065: 'offset' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(85) : error C2065: 'off_t' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(85) : error C2146: syntax error : missing ';' before
identifier 'mxGetScalar'
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(109) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(112) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(112) : error C2065: 'buffer' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(112) : warning C4047: 'function' : 'char *' differs in
levels of indirection from 'int'
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(112) : warning C4024: 'function through pointer' :
different types for formal and actual parameter 2
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(113) : error C2065: 'buffer' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(113) : warning C4047: 'function' : 'const char *' differs
in levels of indirection from 'int'
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(113) : warning C4024: 'mexErrMsgTxt' : different types for
formal and actual parameter 1
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(116) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(126) : warning C4013: 'fseeko' undefined; assuming extern
returning int
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(126) : error C2065: 'offset' : undeclared identifier
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(132) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(133) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(134) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(136) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(140) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(147) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(148) : warning C4090: 'function' : different 'volatile'
qualifiers
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(203) : warning C4018: '<' : signed/unsigned mismatch
C:\Downloads\motr-master\motr-master\Modules\MEX_Code\parsejpg8\parsejpg8.c(255) : warning C4018: '<' : signed/unsigned mismatch

Error in compileMexFunctions (line 144)
mex('-v', ...

Error in motr (line 17)
    compileMexFunctions();
***
Any urgent help is appreciated.

**Comment by adamltaylor** [comment]
I would try installing the MS SDK 8.1, and selecting that using "mex -setup".  Then try running Motr again.

**Comment by adamltaylor** [comment]
Also, be aware that the bulk of the testing of Motr is done on 64-bit operating systems.  So if that's an option, it might be worth it.
